name: addS3BucketAWS

# This is a basic workflow to help you get started with Actions
# Controls when the action will run. 
# not working. says there is an error on line 1
on:
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
    
      - name: Upload to S3
        run: |
           aws s3 mb s3://retail-db-bkt-jtr
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: 'eu-west-2'
